### ISSUE TITLE
OpenCV: FFMPEG: tag 0x00000021

### ISSUE THREAD

**Issue by imtahersiddik** [Tauril/stealth-converter#2]
OpenCV: FFMPEG: tag 0x00000021/'!???' is not found (format 'mp4 / MP4 (MPEG-4 Part 14)')'
Fail to open writer

Getting this error on splitting i tried every way but not working.
How to solve this?

**Comment by Tauril** [comment]
Hello, this is quite an old project, so chances are things are not really up to date with new systems. I just tried on my OS X Catalina device and I was able (after some work to manage to build) to make the program run without modifying the code (following the instructions on the readme).

From what I read on this thread https://stackoverflow.com/questions/61762229/opencv-ffmpeg-tag-0x00000021-is-not-found-format-mp4-mp4-mpeg-4-pa, maybe your system requires to explicitly indicate the codec instead of using the hexcode.

You can try replacing references to
```
0x00000021
```
with

```
int fourcc = CV_FOURCC('m', 'p', '4', 'v');
```

I tried and that worked too

**Comment by imtahersiddik** [comment]
I'm not a programmer.
Can you tell me how to replace this?
Or give me command which will replace this.

**Comment by Tauril** [comment]
Go into the file
```
stealth-converter/src/stream/stream-writer.cc
```
Lines 41 & 83 have both `0x00000021`.
Above each of those lines, do
```
int fourcc = CV_FOURCC('m', 'p', '4', 'v');
```
and then replace the `0x00000021` with `fourcc`

**Comment by imtahersiddik** [comment]
It's worked thanks.
Can you tell me which video path i should give in convert video.
An example of convert video and resemble video can be helpful.
Can you give me a example command of convert and resemble?

**Comment by Tauril** [comment]
The input of the convertion option will be the output videos of the split option. The input of the recombine option will be all the videos you have converted.

```
./stealth-converter -s <path to video>
# generates N videos x
./stealth-converter -c <x1> <x2> <xN>
# generates N videos y
./stealth-converter -r <y1> <y2> <yN>
```

Marking the PR as resolved.

If you have more questions, please open a new issue that'll be dedicated to your questions, since this is irrelevant to the original topic.
